### PR TITLE
Feature/use external stylesheet

### LINKED ISSUE #10000: Page Builder: CSS not loaded
While editing a page in the Page Builder the CSS is not loaded. It is fine once you save, and open the page with the Preview or Live URL.

image

Initial debugging indicates that `getAsssetUrl` is not working:
image

EDIT: 31.8
I further investigated this. And I realized that absolute URLs are also not loaded in the page builder. So it should **not** be about `getAsssetUrl`:
image

### PR DESCRIPTION
**Pull request by adiux**
fixes: #18

How to test
1. load a landing page with an external stylesheet
2. if it looks good in the editor and the final landingpage it works.

### CODE REVIEW

**Comment by RCheesley** [comment]
@adiux while this does fix the issue it also includes CKEditor - I think that was not intentional and maybe some stray commits have made it into this PR.

Could you address that so this PR is just the bug fix?

**Comment by adiux** [comment]
@RCheesley it is just the bug fix now. Would you please have another look?

**Review by RCheesley — APPROVED** [review]
Works perfectly!

One thing to mention but I do not know if it is related to this PR, I am seeing this error in the console when viewing the page:

```
Uncaught ReferenceError: Mautic is not defined
    at Object.parcelRequire.RfSX../builder.service (builder.js:33)
    at f (builder.js:1)
    at parcelRequire.CHLI (builder.js:1)
    at builder.js:1
```

**Comment by RCheesley** [comment]
@adiux could you address the conflicts please (presumably due to the fact that I just merged the PR with the new skin).

**Comment by adiux** [comment]
@RCheesley it is auto generated files. You can overwrite the existing code with the code from this PR (I dont have write access).

**Comment by RCheesley** [comment]
I have tried following the steps that GitHub suggests but nothing is happening - still looking into it!

**Comment by mabumusa1** [comment]
@adiux May you please share the testing steps?

**Comment by RCheesley** [comment]
@adiux please can you make this PR against mautic/mautic - once we decide on how we will deal with the assets that is! Thanks!

**Pull request closed without merging**
