### PR TITLE
Fix yes/no button

### PR DESCRIPTION
**Pull request by kuzmany**
1. Go to emails
2. Try switch off/on 
3. See the error

### CODE REVIEW

**Comment by RCheesley** [comment]
@kuzmany this fixes the problem with the publish yes/no toggle, but it does not fix the same issue (from what I can see in the error message in the console) with the preview link on/off button.

I am guessing that it might be the same code or similar, just used in a different place?

screenshot-nimbus-capture-2021 02 16-23_49_44

**Comment by kuzmany** [comment]
@RCheesley looks like your issue is not related to grapejs

**Comment by kuzmany** [comment]
Why this is not merged and let release it with bug?

**Comment by RCheesley** [comment]
@kuzmany there has not been anyone else test or review this, so it has not been merged yet.

**Comment by RCheesley** [comment]
I am seeing the error before applying the PR:

`[2021-03-27 12:35:47] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 2 passed to Mautic\CoreBundle\Helper\ArrayHelper::getValue() must be of the type array, null given, called in /var/www/html/plugins/GrapesJsBuilderBundle/Model/GrapesJsBuilderModel.php on line 73" at /var/www/html/app/bundles/CoreBundle/Helper/ArrayHelper.php line 27 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in /var/www/html/plugins/GrapesJsBuilderBundle/Model/GrapesJsBuilderModel.php on line 73 at /var/www/html/app/bundles/CoreBundle/Helper/ArrayHelper.php:27)"} []
`
After applying the PR I now get this error in the console (no critical error in the logs any more though)

```
libraries.js?v2fdd2f79:1606 Uncaught TypeError: Cannot read property 'off' of null
    at libraries.js?v2fdd2f79:1606
    at HTMLDivElement.complete (libraries.js?v2fdd2f79:1551)
    at HTMLDivElement.fn (libraries.js?v2fdd2f79:444)
    at HTMLDivElement.handle (libraries.js?v2fdd2f79:1031)
    at HTMLDivElement.dispatch (libraries.js?v2fdd2f79:465)
    at HTMLDivElement.elemData.handle (libraries.js?v2fdd2f79:451)
    at Object.trigger (libraries.js?v2fdd2f79:682)
    at HTMLDivElement.<anonymous> (libraries.js?v2fdd2f79:688)
    at Function.each (libraries.js?v2fdd2f79:153)
    at jQuery.fn.init.each (libraries.js?v2fdd2f79:144)
```

**Comment by kuzmany** [comment]
@RCheesley that issue is not related to this fix. This fix just ajax request on email list page.

**Comment by mabumusa1** [comment]
@RCheesley I can not replicate this issue, what are the steps did you take to replicate it?

**Comment by RCheesley** [comment]
With the GrapesJS builder enabled in developer mode, open your dev tools console and when you are in the list of emails, toggle them from on to off. There was an error thrown in the logs and in the console which this PR should fix - when I tested I found that it threw a different error when the PR was applied which was not there before!

To apply the PR, remove the builder directory if you have it already and then clone this repo into the plugins folder - then pull the PR in the usual way.

**Comment by RCheesley** [comment]
@kuzmany please can you push this PR against mautic/mautic now that the PR has been merged? Thanks!

**Comment by kuzmany** [comment]
Moved https://github.com/mautic/mautic/pull/10023

**Pull request closed without merging**
