### PR TITLE
Redesign GrapesJs to be more like a "Mautic" Builder

### LINKED ISSUE #37: "Light design" UI/color adjustments
<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/96696598-light-design-ui-color-adjustments?utm_campaign=plugin&utm_content=tracker%2F183228013&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F183228013&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alexhammerschmied**
I changed colors and look and feel to the Mautic colors. 
Hope you like it. :)

Fixes #37

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for making the PR - looks like there are some conflicts to be addressed if you could have a look?

**Comment by RCheesley** [comment]
Really nice - thanks for making those changes!

screenshot-mautic32 ddev site-2021 02 15-16_31_51

If you can address the conflicts we could slip this into the initial release!

**Comment by RCheesley** [comment]
@alexhammerschmied do you think you can address the conflicting files in this PR?

**Comment by RCheesley** [comment]
@alexhammerschmied looks like we may miss the opportunity to include this with the Alpha release unless you are able to address the conflicts? 

If that is the case we will have to get this ready for the Beta release as that's when we will be having a lot of users testing.

**Comment by alexhammerschmied** [comment]
Created a new, uptodate PR.

**Pull request closed without merging**
