### PR TITLE
Fix for can not close code preview.

### PR DESCRIPTION
**Pull request by snoblucha**
Once the code preview is opened it can not be closed. 

```
editor.Modal.getContent() 

m [div.gjs-export-dl]
  0: div.gjs-export-dl
  length: 1
```
This object does not have function `querySelector()`

This fix returns the parent element that can be searched with desired querySelector.

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for making this PR @snoblucha - indeed this does fix the code mode not closing! 🎉 

Could you address the conflict and then we can merge the PR :)

**Review by RCheesley — DISMISSED** [review]
Thanks for the fix and the German translation - GTG once the conflict is resolved!

**Comment by snoblucha** [comment]
@RCheesley I merged the changes from mautic3x branch and added Czech translation.

**Review by RCheesley — APPROVED** [review]
Awesome - thank you for doing this work!

**Pull request merged**
