### PR TITLE
Add support mjml in email.html.twig

### PR DESCRIPTION
**Pull request by kuzmany**
This should fix this https://github.com/mautic/mautic/issues/9676
At the moment If you want use MJML you need add to your template email.mjml.twig.

After this PR your template should have email.html.twig with MJML. This allow upload template without issue.
State before I marked as deprecated, we should rename email.mjml.twig to email.html.twig and note it to documentation. 

Steps to tests:

1. Delete brienz theme and upload modified them with renamed email.mjml.twig to email.html.twig
[brienz.zip](https://github.com/mautic/plugin-grapesjs-builder/files/6406871/brienz.zip)

2. Try If template works like before

### CODE REVIEW

**Comment by RCheesley** [comment]
I tried to upload the file attached but still getting the same warning:

screenshot-mautic4 ddev site-2021 04 24-18_21_03

**Comment by RCheesley** [comment]
Maybe the file was not renamed? Or did you mean that we should unzip, rename and upload?

screenshot-nimbus-capture-2021 04 24-18_25_56

**Review by RCheesley — APPROVED** [review]
Confirmed by testing with the theme provided and renaming the MJML file to HTML allowed me to upload the theme, and when I work with the template in the GrapesJS builder I am seeing the MJML markup when I click to view the code mode.

**Comment by kuzmany** [comment]
Seems does not work on edit, even If MJML was stored.  I will check it

**Comment by kuzmany** [comment]
@RCheesley without this PR there is a bug with MJML at current version? If create mjml email, then save & close, then try open builder - open HTML version of editor for me? Can you test it?

**Comment by RCheesley** [comment]
@kuzmany yes I can reproduce that - as soon as I close the builder, without saving the email, it is in HTML - https://youtu.be/yKyTn4qqObI

**Comment by kuzmany** [comment]
@adiux I suppose issue coming from this condition https://github.com/mautic/plugin-grapesjs-builder/blob/d85612e9f18e28c7f44dedd0bf930a116afe0ce5/Assets/library/js/builder.js#L17

Should be something

`  const canvasContent = mQuery('textarea.builder-mjml').val() ? mQuery('textarea.builder-mjml').val() : fullHtml.body.innerHTML;`


How it works on dev mode? I need run `npm run build` on on every change?  Could you look on it?

**Comment by kuzmany** [comment]
@RCheesley @adiux this should fixed it https://github.com/mautic/plugin-grapesjs-builder/pull/76. Can you test also this PR?

**Comment by RCheesley** [comment]
> 1. Delete brienz theme and upload modified them with renamed email.mjml.twig to email.html.twig
>    [brienz.zip](https://github.com/mautic/plugin-grapesjs-builder/files/6370207/brienz.zip)

@kuzmany when I try to upload this file, with this PR applied, I am still getting the error: 
> `The theme you tried to install is missing the following required files and thus could not be installed: html/email.html.twig`

What is this PR supposed to be addressing?

The goal is that folk can upload a theme that is just MJML I think (eg email.mjml.twig), but maybe I am missing something here - did you change it so that the file can be email.html.twig but still contain only MJML?

Would really appreciate some clarity on this both for testing the PR but also for the docs that @jos0405 is working on.

**Comment by kuzmany** [comment]
@RCheesley I uploaded wrong theme 
[brienz.zip](https://github.com/mautic/plugin-grapesjs-builder/files/6406872/brienz.zip) 

Now MJML code is paste directly in  email.html.twig - this is my change. 
If you want standard HTML editor for email you just put HTML to email.html.twig. If you need MJML editor for email, you just put MJML to email.html.twig.
Code detect syntax and choose builder based on that.

**Comment by RCheesley** [comment]
Awesome - works great with that installer for the theme - was able to create the theme, and MJML markup is retained after saving also. There is still the issue with the device preview but will raise that as a separate issue.

**Pull request merged**
