### PR TITLE
Refactor to service with linting and fixes

### LINKED ISSUE #51: Landing page has no builder button until you press 'apply'
In the email builder we have a Builder button from as soon as the create email screen opens:

screenshot-mautic32 ddev site-2021 02 13-23_32_06

In the landing page builder this does not show, which is rather confusing, until we press apply.

screenshot-mautic32 ddev site-2021 02 13-23_32_40

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/96696578-landing-page-has-no-builder-button-until-you-press-apply?utm_campaign=plugin&utm_content=tracker%2F183228013&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F183228013&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by adiux**
I did some Javascript refactoring. I mostly moved functionality to a service.

This meant I had to improve on the tooling as well. So I also added a package manager (npm), linting (eslint), formatter (prettier), compiler (babel), and a web application bundler (parcel).

I'm aware that this is a lot of code change. But I think it is necessary to deliver good quality code in the future. Also regarding the loading time.

It would be good if we can merge this PR as soon as possible. It will give conflicts with many new changes.

Fixes #51

### CODE REVIEW

**Comment by kuzmany** [comment]
Something special to know to test?

See conflicts already :(

**Comment by adiux** [comment]
yes. it will be annoying to merge. 

I'm not done with all the refactoring. Working on some last fixes now.

At this point, I wanted to start a discussion about code structure, linting, and package manager.

**Comment by RCheesley** [comment]
Are we good to go with testing now? Are there any specific things we should be looking to check?

**Comment by adiux** [comment]
@RCheesley yes we are. It is supposed to be the same functionality as before (hopefully with a couple of fixes on the way).

General testing: no errors in the console or any other errors in the UI.

**Comment by RCheesley** [comment]
Great, I'll look at testing tomorrow!

**Comment by alexhammerschmied** [comment]
Looks good to me. 
Only thing i want to mention:
In the Landingpage Builder is  the "Forms" Function available now. This is confusing, because it actually doesn't work out of the box with Mautic. 
But the rest looks great. Thank you for that!

**Review by alexhammerschmied — CHANGES_REQUESTED** [review]
I suggest to change the value "allowScripts:0" to  "allowScripts:1" inside the "Assets/library/js/dist/builder.js" file. It is too big the edit it directly in here...

This makes javascript executable in the landingpages.

The rest looks good to me :)

**Comment by adiux** [comment]
@alexhammerschmied forms are fixed. I will take a look at the code option once the refactoring is merged.

This PR depends on: https://github.com/mautic/grapesjs-preset-mautic/pull/1

**Comment by RCheesley** [comment]
@adiux it would be super helpful to have some instructions on how to test this and the dependant PR so that we can get these fixes merged asap - could you share?

**Comment by adiux** [comment]
@RCheesley the PR is only a small fix that became necessary once I switched to the "modern" implementation. But it needs to be merged first, or things will break here (with the plugin). From my side we can simply do a code review for that.

For the refactoring here: I did not change anything from the functionality. Basically, it should all work the same as before. So it will be enough to click through the application to see if anything brakes.

So far I realized there is an issue with the filter criteria drop down for the dynamic content. This is related to Froala. And it is not the only issue related to that.

Based on our decission at last weeks meeting, I'm working right now on replacing Froala with Ckeditor4. It woul be great to get some support here. Specially for the dynamic content part.

**Comment by RCheesley** [comment]
OK re. the tweaks to the preset - will check if Dennis did a code review as part of the workflow implementation!

Great re. the Froala/CKEditor side of things also, will see if anyone at Acquia may be able to assist!

**Comment by alanhartless** [comment]
@adiux would you please create an issue describing what you're experiencing? It'll likely take some debugging to address the problem(s).

**Comment by RCheesley** [comment]
With the builder applied on M4 (working fine before applying the PR) and then applying this PR, I am getting this issue when I click to open the builder:

https://youtu.be/eyEgejsz3A8

```
builder.js:31 Uncaught Error: No HTML or MJML content found
    at new i (builder.js:31)
    at Object.a [as launchBuilder] (builder.js:33)
    at HTMLButtonElement.onclick (VM4480 emails:1)
    at Object.trigger (2.jquery.js:8255)
    at HTMLButtonElement.<anonymous> (2.jquery.js:8327)
    at Function.each (2.jquery.js:354)
    at jQuery.fn.init.each (2.jquery.js:189)
    at jQuery.fn.init.trigger (2.jquery.js:8326)
    at jQuery.fn.init.jQuery.fn.<computed> [as click] (2.jquery.js:10212)
    at HTMLButtonElement.buttonClick (1a.content.js:557)
```

**Comment by RCheesley** [comment]
Good to go - that error was due to a bug with the naming of the Blank theme which has an open PR to address it: https://github.com/mautic/mautic/issues/9741

**Review by RCheesley — APPROVED** [review]

**Pull request merged**
