### PR TITLE
Code mode support

### LINKED ISSUE #44: Code Mode does not work If plugin is enabled
Code Mode opened by GrapeJs edit as well.  Expect open good old Code Mode builder

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/96696593-code-mode-does-not-work-if-plugin-is-enabled?utm_campaign=plugin&utm_content=tracker%2F183228013&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F183228013&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #50: Builder does not allow code mode as an option where no compatible theme is available
Noticed that when there is no compatible theme available it is not possible to see Code Mode, which makes no sense:

screenshot-mautic32 ddev site-2021 02 13-23_30_36

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/96696579-builder-does-not-allow-code-mode-as-an-option-where-no-compatible-theme-is-available?utm_campaign=plugin&utm_content=tracker%2F183228013&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F183228013&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kuzmany**
This PR added support for code mode 
We need it also due BC, because a lot of users use code mode and after upgrade they loose this option.

image

1. Create email with mjml template
2. Switch to code mode
3. Should open regular code mode window like in M3

@adiux probably you can make it more clean

### CODE REVIEW

**Comment by adiux** [comment]
Do we need code mode? Grapesjs has an import feature. IMO this replaces code mode:
https://grapesjs.com/demo-newsletter-editor.html

Open it by clicking on the icon with the arrow.
image

**Comment by kuzmany** [comment]
@adiux What about users whose use emails  code mode in M3? They use tokens etc. That means after migrate to M4 their start use GrapesJs.

I am a fan to use just GrapesJs  and cut legacy/code mode builder, because in fact, there are a lot of works and not dev resources to maintenance it. 

We need decision.

**Comment by adiux** [comment]
Im just starting to learn how dynamic content works in detail. My understanding is that a token ‘{dynamic content…}‘ is saved in the html in the DB. On page load grapesjs has to recognize this token in the HTML as dynamic content. 

I assume this is the same for theme and code mode?

It would be great if we can cut some complexity!

**Comment by kuzmany** [comment]
@adiux dynamics content is not related to this PR but in summary:

If you switch to code mode you see 3th tab Dynamic Content

image

This is used for all Dynamic content in Legacy builder/GrapesJs builder. In fact, just copy DOM contents from that tab and put it to the place where you see it in builders, and after close builder, put the changes back to that tab.

Data are stored to emails table > dynamic_content column, and dynamics filters are rebuild from that.

**Comment by RCheesley** [comment]
I would also favour removing the code mode and having folks use the GrapesJS code mode. 

We will need to push this PR up to mautic/mautic once we merge https://github.com/mautic/mautic/pull/9966 (which needs test coverage - the builder is currently at -0.11% so we can't bring it into core until that is raised).

**Comment by RCheesley** [comment]
Closing this PR in favour of using GrapesJS built in feature - please make that PR against mautic/mautic.

**Pull request closed without merging**
