### PR TITLE
GrapesJs as default builder

### PR DESCRIPTION
**Pull request by kuzmany**
Requires this PR on Mautic side: https://github.com/mautic/mautic/pull/9935

#### Steps to test this PR:
1. Clone Mautic locally
2. cd to the plugins directory
2. Remove the GrapesJS plugin and clone this repo: https://github.com/mautic/plugin-grapesjs-builder into the folder `GrapesJsBuilderBundle` - can be done using `gh repo clone mautic/plugin-grapesjs-builder GrapesJsBuilderBundle` if you have GitHub CLI installed
3. cd into the `GrapesJsBuilderBundle` directory
3. Apply the PR https://github.com/mautic/plugin-grapesjs-builder/pull/79 - can be done using `gh pr checkout 79` if you have GitHub CLI installed
2. cd back to Mautic's root directory
2. Apply this PR https://github.com/mautic/mautic/pull/9935 - can be done using `gh pr checkout 9935` if you have GitHub CLI installed
3. GrapesJs should now be the default builder without additional changes being needed (enable/disable)...

GrapesJs plugin is not as integrations anymore. By default is loaded with related themes (no builder in config, or grapesjsbuilder in config)
Not need enable/disable plugin.  Any themes by default are open by GrapesJs If any builder integration is not enabled.
Should cleanup set of themes in M4 or do we include all current themes?

### CODE REVIEW

**Review by RCheesley — COMMENTED** [review]
Added some test instruction to both PRs to make it hopefully easier for folks to test them both.

✅    PR worked as described, the editor is the default and shows enabled in the plugins section:

screenshot-mautic4 ddev site-2021 04 30-19_36_53

❓   There does not, however, seem to be any option to disable the new builder - is that by design? I thought that we had agreed to allow people to disable and switch it back to the Legacy builder if they wanted to (or use their own builder), until Mautic 5, when we would physically remove the code from the codebase.

This may not be an issue if we are making all of the existing themes accessible in the new builder, however (but see #83 for a bug with this) but I thought it would be good just to double check this point.

**Comment by kuzmany** [comment]
If we want remove legacy builder in future version, then there is no step back to  use legacy builder. We do not have time to maintenance two builders. Anybody can add builder by plugin and replace grapesjs.

**Comment by adiux** [comment]
I think we did discuss that. But if I remember correctly we said that we might leave the option to deactivate it, if it is not too complicated to maintain. For starters there is also the issue/dependency with Froala. So the old builder will need that RTE to work. Did we decide to remove Froala with M4?

How can people switch to another builder if we can not deactivate Grapesjs?

**Comment by RCheesley** [comment]
@adiux the PR for introducing CKEditor is already merged: https://github.com/mautic/mautic/pull/9843 so that part is already dealt with.

> But if I remember correctly we said that we might leave the option to deactivate it, if it is not too complicated to maintain.

Indeed, that is what we had agreed, but this PR seems to not allow you to disable GrapesJS. Folks could install another plugin to use a different builder but there is no way (it seems) to disable GrapesJS.

@kuzmany has this removed **all** the code relating to the legacy builder, or just some parts?

**Comment by kuzmany** [comment]
This not removed legacy builder close. Then close it and need create another PR

**Comment by adiux** [comment]
>https://github.com/mautic/mautic/pull/9843
>Deprecations
>Froala is on its way out so nothing new should be dependent on it.

So it looks like Froala is still available, but deprecated. So technically people could still use the old builder. 👍

**Comment by RCheesley** [comment]
@kuzmany will you be able to provide a new/updated PR to enable the GrapesJS builder by default and allow folk to disable the plugin at will, while retaining the legacy builder? 

This is what has been agreed in our calls throughout the initiative and communicated to stakeholders. The legacy builder will be completely removed in Mautic 5.

**Comment by RCheesley** [comment]
@kuzmany whichever way we go, please can you make the PR against mautic/mautic? Thanks!

**Pull request closed without merging**
